# Site settings
title: Grupo de Etnobot√¢nica - Jardim Bot√¢nico do Rio de Janeiro
description: "Site do grupo de pesquisa em Etnobot√¢nica e da Cole√ß√£o Tem√°tica de Plantas Medicinais do Jardim Bot√¢nico do Rio de Janeiro (JBRJ)."
author: Viviane S. Fonseca Kruel

# URL do seu dom√≠nio principal (sem a barra final "/")
url: "https://etnobotanicajbrj.github.io/"

# Base URL
# Se seu site n√£o estiver no dom√≠nio principal, use o nome do reposit√≥rio
baseurl: "/medicinais_jbrj.github.io" 
# Exemplo se o reposit√≥rio fosse 'meu-projeto': baseurl: "/meu-projeto"

# Build settings
# O tema √© essencial. Voc√™ pode usar um tema padr√£o como "minima"
theme: minima

# Exclus√µes
# Arquivos ou pastas que o Jekyll deve ignorar
exclude:
  - Gemfile
  - Gemfile.lock

# Links de Navega√ß√£o do Site
nav_links:
  - title: Sobre
    url: /sobre/
  - title: Equipe
    url: /equipe/
  - title: Publica√ß√µes
    url: /publicacoes/
  - title: Visite a Cole√ß√£o!
    url: /visite/
  - title: Contato
    url: /contato/

plugins:
  - jekyll-sitemap

# --- Configura√ß√£o do Menu Lateral (Sidebar) ---
sidebar_nav:
  - title: Home
    url: /
  - title: Sobre
    url: /sobre/    
  - title: Equipe
    url: /equipe/
  - title: Publica√ß√µes
    url: /publicacoes/
  - title: Visite a Cole√ß√£o!
    url: /visite/
  - title: Contato
    url: /contato/
# üí° NOVO: Adicione o link e o √≠cone do Instagram
  - title: Instagram
    url: https://www.instagram.com/etnobotanicajbrj?igsh=MWxvMzA3Mms4a3AwMA== # Lembre-se de mudar o URL
    icon: fab fa-instagram
    external: true # Marcador opcional para indicar link externo
